# Dockerfile.predict
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY predict.py predict.py
COPY model.pkl model.pkl

CMD ["python", "predict.py"]